# Generated by Django 2.1.5 on 2019-10-30 14:35

from django.db import migrations, models
import django.utils.timezone
import myauth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='メールアドレス')),
                ('name', models.CharField(max_length=150, verbose_name='名前')),
                ('furigana', models.CharField(max_length=150, verbose_name='フリガナ')),
                ('birthday', models.DateField(null=True, verbose_name='生年月日')),
                ('address', models.CharField(max_length=150, null=True, verbose_name='住所')),
                ('phone', models.CharField(max_length=50, null=True, verbose_name='連絡先電話番号')),
                ('clinic_name', models.CharField(max_length=100, null=True, verbose_name='歯科医院名')),
                ('thumbnail', models.ImageField(null=True, upload_to='profile_thumbnail', verbose_name='サムネイル')),
                ('is_online', models.BooleanField(default=False, verbose_name='オンライン')),
                ('alert_freq', models.CharField(choices=[('0', '通知しない'), ('1', '毎回'), ('2', '30分に1回'), ('3', '1時間に1回')], default=0, max_length=50, verbose_name='通知頻度')),
                ('last_alerted', models.DateTimeField(null=True, verbose_name='最終通知時間')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='管理者')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='有効')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'ユーザ',
                'verbose_name_plural': 'ユーザ',
            },
            managers=[
                ('objects', myauth.models.MyUserManager()),
            ],
        ),
    ]
