# Generated by Django 2.1.5 on 2019-11-28 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='alert_freq',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='user',
            name='clinic_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='furigana',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_alerted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
