# Generated by Django 2.1.5 on 2019-05-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_auto_20190522_1904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'verbose_name': 'トークルームメッセージ', 'verbose_name_plural': 'トークルームメッセージ'},
        ),
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'トークルーム', 'verbose_name_plural': 'トークルーム'},
        ),
        migrations.AlterModelOptions(
            name='chatroommember',
            options={'verbose_name': 'トークルームメンバ', 'verbose_name_plural': 'トークルームメンバ'},
        ),
        migrations.RemoveField(
            model_name='chatroommember',
            name='is_online',
        ),
        migrations.AddField(
            model_name='chatroommember',
            name='is_reading',
            field=models.BooleanField(default=False, verbose_name='入室中'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='オンライン'),
        ),
    ]
