# Generated by Django 2.1.5 on 2019-05-27 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_auto_20190526_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_alerted',
            field=models.DateTimeField(null=True, verbose_name='最終通知時間'),
        ),
    ]
