# Generated by Django 2.1.5 on 2019-05-29 04:13

from django.db import migrations, models
import django.utils.timezone
import unixtimestampfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0004_user_last_alerted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sent_at',
            field=unixtimestampfield.fields.UnixTimeStampField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='chatroommember',
            name='last_logout',
            field=unixtimestampfield.fields.UnixTimeStampField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='alert_freq',
            field=models.CharField(choices=[('0', '通知しない'), ('1', '毎回'), ('2', '30分に1回'), ('3', '1時間に1回')], default=0, max_length=50, verbose_name='通知頻度'),
        ),
    ]
