# Generated by Django 2.1.5 on 2019-05-29 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_auto_20190529_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='sent_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chatroommember',
            name='last_logout',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='最終ログアウト時間'),
        ),
    ]
