# Generated by Django 2.1.5 on 2019-10-30 14:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='upload', verbose_name='ファイル')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
            ],
            options={
                'verbose_name': '添付ファイル',
                'verbose_name_plural': '添付ファイル',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'トークルームメッセージ',
                'verbose_name_plural': 'トークルームメッセージ',
            },
        ),
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'トークルーム',
                'verbose_name_plural': 'トークルーム',
            },
        ),
        migrations.CreateModel(
            name='ChatRoomMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_logout', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='最終ログアウト時間')),
                ('is_reading', models.BooleanField(default=False, verbose_name='入室中')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='chat.ChatRoom')),
            ],
            options={
                'verbose_name': 'トークルームメンバ',
                'verbose_name_plural': 'トークルームメンバ',
            },
        ),
    ]
