# Generated by Django 2.1.5 on 2019-11-28 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_thumbup'),
    ]

    operations = [
        migrations.AddField(
            model_name='thumbup',
            name='room',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chat.ChatRoom'),
            preserve_default=False,
        ),
    ]
